name = "gbr_mcp"
version = "1.0.0"

description = "ðŸ§  MCP Server/Client builder"
licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
links = []

[dependencies]
gbr_json = { path = "../gbr_json" }
gbr_shared = { path = "../gbr_shared" }

pollux = "~> 1.0"
simplifile = "~> 2.3"

gleam_stdlib = "~> 0.68"
gleam_json = "~> 3.1"

[dev-dependencies]
gleeunit = "~> 1.9"
