name = "gbr_mcp"
version = "1.0.0"

description = "ğŸ§  MCP Server/Client builder"
licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
links = []

[dependencies]
gleam_stdlib = "~> 0.68"
simplifile = "~> 2.3"
castor = "~> 1.0"
gleam_json = "~> 3.1"
oas_generator = ">= 2.3.0 and < 3.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.9"
